version: "3"

services: 
  api:
    container_name: lighthouseapi
    image: lighthouseapi
    build:
      context: .
      dockerfile: Equinor.Lighthouse.Api.WebApi/Dockerfile
    ports:
      - "8080:5000"
