version: "3"

services: 
  api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - AZURE_CLIENT_SECRET=${AZURE_CLIENT_SECRET}
      - AZURE_TENANT_ID=3aa4a235-b6e2-48d5-9195-7fcf05b459b0
      - AZURE_CLIENT_ID=${AZURE_CLIENT_ID}
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets/e47b709b-5c82-4a61-935c-823e332955f9/:/home/apprunner/.microsoft/usersecrets/e47b709b-5c82-4a61-935c-823e332955f9/